services:

  db:
    image: postgres:16-alpine
    container_name: djangotemplate_postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=foobar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d db"]
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 5432
    ports:
      - 5432:5432  # Required for running Django outside Docker but using PostgreSQL
    volumes:
      - djangotemplate_postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    image: brecheisen/djangotemplate-nginx-intel:latest
    platform: linux/amd64
    container_name: djangotemplate_nginx
    ports:
      - 8000:8000
    volumes:
      - djangotemplate_data:/data
    depends_on:
      - web

  web:
    build: .
    image: brecheisen/djangotemplate-web-intel:latest
    platform: linux/amd64
    container_name: djangotemplate_web
    environment:
      - DATA_DIR=/data
      - POSTGRES_DB=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=foobar
      - POSTGRES_HOST=mosamatic3_postgres # When you run Django in Docker set the host
      - POSTGRES_PORT=5432
      - REDIS_HOST=mosamatic3_redis
      - DOCKER=1
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=admin
      - SECRET_KEY=1234
    volumes:
      - djangotemplate_data:/data
    depends_on:
      db:
        condition: service_healthy

volumes:
  djangotemplate_data:
  djangotemplate_postgres_data:

networks:
  default:
    name: djangotemplate